//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockEdge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpTbl
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public System.DateTime DateOfJoining { get; set; }
        public bool IsCurrentEmp { get; set; }
        public decimal AnnualSalary { get; set; }
        public Nullable<int> DepartmentID { get; set; }
    
        public virtual EmpDepTbl EmpDepTbl { get; set; }

        public int Year { get; set; }
        public int Month { get; set; }
    }
}
